version = 0.1
[default.deploy.parameters]
stack_name = "memorydb-lambda"
resolve_s3 = true
s3_prefix = "memorydb-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MemoryDBEnpoint=\"\""
image_repositories = []
