AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  memorydb_loader

  MemoryDB client

Globals:
  Function:
    Timeout: 600
    MemorySize: 256
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  MemoryDBHost:
    Type: String
    Description: MemoryDB host
  SecurityGroupId:
    Type: String
    Description: Security Group Id
  Subnet:
    Type: String
    Description: Subnet


Resources:
  LoaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
#      Events:
#        ScheduleEvent:
#          Type: ScheduleV2
#          Properties:
#            ScheduleExpression: "rate(5 minutes)"
#        Repeat:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /repeat
#            Method: get
      VpcConfig:
        SecurityGroupIds:
        - !Ref SecurityGroupId
        SubnetIds:
        - !Ref Subnet
      Environment:
        Variables:
          MEMORYDB_HOST: !Ref MemoryDBHost
      Policies:
       - CloudWatchPutMetricPolicy: {}



  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  Lambda:
    Description: Any message
    Value: Lambda deployed